services:
  postgres:
    image: postgres:16-alpine
    container_name: loan-application-postgres
    environment:
      POSTGRES_DB: loan_application_app
      POSTGRES_USER: loan_app
      POSTGRES_PASSWORD: loan_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
